### PR TITLE
GridSharedData needs to be default constructible

### PR DESCRIPTION
**Pull request by sithhell**

### CODE REVIEW

**Comment by sithhell** [comment]
ping?

**Comment by HerbertJordan** [comment]
Sorry, have been busy lately ...
Conceptional the shared data should not need a default constructor, since instances are created by a user code call passing along init parameters and from that point on only moved / serialized / deserialized / destructed. As usual, for the grid adding a default constructor is no big deal, but I would not assume that any shared data is default-construable.

Unfortunately nobody is available to work on the mesh example :(

**Comment by sithhell** [comment]
I need the default ctor in order to serialize it.

**Comment by HerbertJordan** [comment]
Old question: can't the present API serialization mechanism be used?
I can merge it, but if you then generally assume that shared data objects have default constructors, we will have to adapt other shared data classes in the future.

**Comment by sithhell** [comment]
Without this, the runtime can't use any Data Items that don't have a default constructor for their shared data type.

**Comment by HerbertJordan** [comment]
This is not to be taken as a precedence nor agreement to the requirement that shared data types need default constructors. I just have other battles to fight than that.

**Pull request merged**
